### ISSUE TITLE
Add tags

### ISSUE THREAD

**Issue by milouse** [heychrisd/Boston-Icons#1]
Thank you very much for your hard work !

In order to simplify release process on various linux distribution, can you add git tags, pointing to your release? Thanks again!

**Comment by thecheis** [comment]
As I say [in the wiki](https://github.com/heychrisd/Boston-Icons/wiki/Questions-and-answers#exist-differences-between-opendesktop-releases-and-github-repoclones), my preference is the OpenDesktop.org package for various reasons. It would be great if you could use that package. But yes, I'll try to do my best to improve Git notifications to simplify packagers work.

Thanks a lot to you!

**Comment by milouse** [comment]
Sorry, I didn't see your FAQ.

However, it is not possible currently to automatically download file from OpenDesktop (with curl or wget), thus it may require for a package maintainer to host **your** file on another file hosting provider, what doesn't sound right :/ 

On the other hand, github provide open URLs allowing package maintener to easily download tag tarball, or even your own package.

Thus, it could be great if you reconsider your position. Thank you very much!
