### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by JatinKhajuria** [heychrisd/Boston-Icons#2]
**Please, be sure your question isn't a bug report or a feature request! For that, use another template.**

What do you want to know more about?
I am using ubuntu 18.04 .When I select this icon pack in gnome tweaks icons dont change.Please help.

**Comment by thecheis** [comment]
Hi.

Probably is a common issue with GNOME cache. This should be solved with a restart (OS or the session).

**Comment by JatinKhajuria** [comment]
I did that but nothing works.Only numix icon theme is working.

**Comment by thecheis** [comment]
I test it and your bug doesn't appear to me.

Can you try the gtk-update-icon-cache?

https://developer.gnome.org/gtk3/stable/gtk-update-icon-cache.html

**Comment by JatinKhajuria** [comment]
Thanks, I will try this.
