### ISSUE TITLE
An icon for terminal and file explorer?

### ISSUE THREAD

**Issue by simurgh9** [heychrisd/Boston-Icons#3]
I love the minimalism of your theme, though there are two glaring omissions as a GNU/Linux user for me. There are no icons for the terminal emulator, e.g., gnome terminal and a file explorer, e.g., nautilus. Is there anyway these icons could be included?

Thanks!

**Comment by thecheis** [comment]
Hi! Thanks a lot for use Boston and your support (and request, of course).

Well, as you [can see reading the wiki](https://github.com/heychrisd/Boston-Icons/wiki#production-priorities) about "production priorities" and "target users", common app icons for GNOME are respected by project's philosophy. I avoid to make app icons that exist and are good in GNOME/Adwaita (remember, quality over quantity). My opinion: style of Adwaita app icons are, in general, very good designed. Boston only covers those which have low quality details (very bad resolution, outdated design, etc).

If you consider that Boston should be got their own icons for those apps which you are saying (whatever desktop you use), please, share with me your opinions and I'll be happy to consider it for the future. Boston icons for terminal or file manager will be better than Adwaita ones? Honestly, I think not. But I remember: I'm open about arguments to consider it.

Once more, thanks a lot.

**Comment by simurgh9** [comment]
I think Boston's style is more sober than Adwaita. The terminal in Adwaita has a shine effect and a thick border with gradient which IMHO does not go with Boston's look. Similarly, for the file manager, Boston has a more square profile for non-file type icons where the two drawer icon looks just smaller and rectangular. I think this desktop icon has the good amount of border that a terminal icon should have and could be easily adapted for a terminal.
![term](https://user-images.githubusercontent.com/43047754/110875669-ae417800-829b-11eb-9b0b-7b379171c88d.png)

On quality over quantity, to me certain icons are the face of an icon theme. So a quality terminal, file-manager, rubbish bin, *.text and *.pdf will contribute to the quality.

PS: If you are really feeling kind, do something for an Emacs icon pls...

**Comment by thecheis** [comment]
Ooops, sorry for the delay. There are good points in your opinions. I'll try to do something about it (I need to do various test, implementations, etc).

I cannot promise final results without study them, but I take notes about your point of view.

Thanks!

**Comment by thecheis** [comment]
Hi again.

After a lot of test, by the moment I'm not convinced about the results. I think Adwaita icons for these apps should be the proper ones till i have better designs.

I'm not closed about the idea in the future, maybe like optional icons. I'm testing other ones with similar ideas and must be refined, so I need more time to study a good design. By the moment aren't a priority (I prefer to polish the basic collection for version 1.0).

I hope to incorporate those optional extras in future versions after the next release.

Thanks for your feedback, and stay close to the project!

Best regards.

**Comment by simurgh9** [comment]
Could you give me a link to Adwaita icons you think these are intended to be used with? There seem to be many versions out there.

**Comment by thecheis** [comment]
Personally, I always use the latest versions of GNOME, with their corresponding Adwaita icons.

**Comment by simurgh9** [comment]
Assuming you're on some type of Debian, could you return the output of `apt list adwaita-*`?

**Comment by thecheis** [comment]
No, I never use Debian derivatives, only Arch (and Fedora to easily acquire GNOME betas).

As I said, my main system always run the latest version available, now GNOME 40.4 with version 40.1 of Adwaita icons.

My Fedora 35 Rawhide virtual installation runs GNOME  41 beta.
